### PR TITLE
Merge static analysis image contents with development images

### PR DESCRIPTION
**Pull request by martyngigg**
Cppcheck is now taking along time to run and would benefit from access to more nodes.

These changes put the static analysis tools in the development image, also giving access to the same tools for developers, so that any node running that image can run the analysis.

**Test**

I have not yet pushed the images. I built Ubuntu locally and ran the cppcheck build script and it produced the expected number of warnings and HTML report.
I would appreciate a second pair of eyes before pushing the new images.

### CODE REVIEW

**Comment by DavidFair** [comment]
Can we move `dockerfiles/jenkins-node/docker-images/os-builder` up a level to `dockerfiles/jenkins-node/docker-images` since we now have a single Jenkins image?

**Comment by DavidFair** [comment]
We need to include pre-commit into the images, at least for CentOS it's no pre-installed and prevents CMake finishing on the development image

**Comment by martyngigg** [comment]
> We need to include pre-commit into the images, at least for CentOS it's no pre-installed and prevents CMake finishing on the development image

Thanks for the pre-commit reminder - I had forgotten we only included it in the Ubuntu ones. This will also gives us more nodes to be able to do that.

**Review by DavidFair — APPROVED** [review]
I've check cppcheck and flake8 on both and did a complete all / AllTests on CentOS

These both worked fine

**Pull request merged**
